FROM node:22-slim AS builder
WORKDIR /app

COPY ../../package*.json ./
RUN mkdir -p apps/backend
COPY package*.json ./apps/backend/
RUN npm install
COPY . ./apps/backend/

RUN npm run build

FROM node:22-slim
WORKDIR /app

COPY --from=builder /app/apps/backend/dist ./dist
COPY package*.json ./

RUN npm install --omit=dev

EXPOSE 3000

CMD [ "node", "dist/app/index.js" ]