FROM node:22-slim AS builder
WORKDIR /app

COPY package.json package-lock.json* ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/

COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/prettier-config/package.json ./packages/prettier-config/
COPY packages/vitest-config/package.json ./packages/vitest-config/

RUN npm install

COPY . .

RUN npm run build --workspace=backend

RUN npm prune --production

FROM node:22-slim
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/backend/dist ./dist
COPY --from=builder /app/apps/backend/package.json ./package.json

USER node

EXPOSE 3000

CMD [ "node", "dist/app/index.js" ]